
services:
  - type: web
    name: noise-sense
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_MAPBOX_ACCESS_TOKEN
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_OPENROUTER_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
